### ISSUE TITLE
Questions..?

### ISSUE THREAD

**Issue by Moikapy** [Larkenx/Rotten-Soup#52]
- Would you mind if I moved the Current Rotten-Soup Projects to the Organization level since they will be for both the desktop and web versions.

- Thoughts on a Discord Server and Bot that relays updates to the Org as well as providing a space for people to interact.

**Comment by Larkenx** [comment]
Sounds good on both accounts

**Comment by Larkenx** [comment]
Here's a discord server I just created https://discord.gg/sWk82a

**Comment by Moikapy** [comment]
Would you be able to create a Dev Team in the Org so that I may have write access to the repo?

**Comment by Larkenx** [comment]
https://github.com/orgs/rotten-soup/teams/dev-team created
