### ISSUE TITLE
Is the lich unkillable?

### ISSUE THREAD

**Issue by SHJordan** [Larkenx/Rotten-Soup#77]
Hi I've tried hitting him with arrows, Bessy, and offensive spells... none have hit him... already explored both mulbery and orc dungeon. Is this where the beta end?

**Comment by Larkenx** [comment]
hey @SHJordan! the Lich is actually killable, albeit incredibly difficult... He both regenerates HP and uses vampirism so really the only way to kill him right now is to use Bessy + stack strength potions + berzerker and rush in there from what I have found. Thanks for playing though! glad you got some fun out of it. hoping to revisit this game one day when I have more free time to do development

**Comment by SHJordan** [comment]
hahaha... still in the log it seems only lich is attacking me... T_T
![image](https://user-images.githubusercontent.com/884602/72163433-9a05a080-33a2-11ea-9864-7be925777a1c.png)

**Comment by Larkenx** [comment]
Just checked it out and I think you are exactly right! Let me take some time to fix that later today and I'll keep ya updated :) It appears the Lich is invincible...which is terrifying

**Comment by SHJordan** [comment]
ty <3

**Comment by Larkenx** [comment]
Fixed in https://github.com/Larkenx/Rotten-Soup/commit/085e16edb41219282812ee81d92e7a2a0d17abce. Go and chop the Lich down with Bessy and find what awaits you as a reward...
