### ISSUE TITLE
Few small questions :)

### ISSUE THREAD

**Issue by Carl-Bowen** [Larkenx/Rotten-Soup#79]
.

**Comment by MisterEmpyrean** [comment]
After some further playing I've answered questions 1, 4, and 6 myself x)

1. Walk on an item and press 'g'
4. Find the stairs (they were well camoflaged for me haha)
6. The game plays a bit naughtily on my screen, had to CTRL + - to zoom out a bit, where I noticed the chat/info/instructions panel on the right-side.

I am all the more impressed. Bless you Larkenx!

I would like to convert this to a React project, wish me the best :)

**Comment by MisterEmpyrean** [comment]
@Larkenx Cheers
